config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :tasks
  # get '/tasks', to: 'tasks#index'

  # get '/tasks/new', to: 'tasks#new'

  # get '/tasks/:id', to: 'tasks#show', as: 'task'

  # post '/tasks/', to: 'tasks#create'

  # get '/tasks/:id/edit', to: 'tasks#edit', as: 'edit'

  # patch '/tasks/:id', to: 'tasks#update'

  # delete 'tasks/:id', to: 'tasks#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  validates :description, presence:true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    # no view needed
    @task = Task.new(task_params)
    @task.save
    redirect_to tasks_path
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    # @task.update({description: params["task"]["description"], is_done: params["task"]["is_done"]})
    # other possibility is to use just one word to get the params but permitted
    @task.update(task_params)
    @task.save
    redirect_to tasks_path
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:description, :is_done)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<%= form_for(@task) do |f| %>
  <%= f.label :new_description %>
  <%= f.text_field :description %>

  <%= f.label :new_status %>
  <%= f.text_field :is_done %>

  <%= f.submit %>
<% end %>

app/views/tasks/index.html.erb
<ul>
  <% @tasks.each do |task| %>
    <li>
        <% if task.is_done %>
        [X]
        <% else %>
        [ ]
        <% end %>
      <%= task.id %>: <%= task.description %> :
      <%= link_to "Voir", task_path(task.id)%>
      <%= link_to "Update", edit_task_path(task.id)%>
      <%= link_to "Delete", task_path(task),
      method: :delete,
      data: { confirm: "Es-tu sûr de vouloir effacer cette tâche?" } %>
    </li>
  <% end %>
</ul>
<%= link_to "Create new task", tasks_path %>

app/views/tasks/new.html.erb
<%= form_for(@task) do |f| %>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <%= f.submit %>
<% end %>

app/views/tasks/show.html.erb
<h2> <% if @task.is_done %>
  [X]
  <% else %>
  [ ]
  <% end %>
  : <%=@task.description %>
  : créé le <%= @task.created_at.strftime('%a %d %b %Y') %>
</h2>
<%= link_to "Retour à l'index", tasks_path %>